### ISSUE TITLE
Randomly stops working, lots of errors in console, completely broken

### ISSUE THREAD

**Issue by teo1978** [vimeo/player.js#689]
### Expected Behavior

The SDK should work

### Actual Behavior

At random times, an endless stream of identical errors like these starts showing up in the Javascript console:

```
DOMException: Failed to read the 'buffered' property from 'SourceBuffer': This SourceBuffer has been removed from the parent media source.
    at n.i.getSegmentsToLoad (https://f.vimeocdn.com/p/3.24.14/js/player.js:10:97165)
    at https://f.vimeocdn.com/p/3.24.14/js/player.js:10:123085
Promise.catch (async)
i.Rr @ player.js:10
(anonymous) @ player.js:10
Promise.then (async)
i.Ke @ player.js:10
i.or @ player.js:10
(anonymous) @ player.js:10
setInterval (async)
i.mr @ player.js:10
i.Fe @ player.js:10
i.play @ player.js:10
n.play @ player.js:10
play @ player.js:10
play @ player.js:10
g @ player.js:10
S @ player.js:10
(anonymous) @ player.js:10
(anonymous) @ player.js:10
t.fire @ player.js:10
(anonymous) @ player.js:10
u @ player.js:10
(anonymous) @ player.js:10
(anonymous) @ player.js:10

```

The video starts buffering and it never resumes playing, even if you hit pause and then play or try to skip to any point in the seekbar using the playbar.

### Steps to Reproduce

I think you can systematically reproduce this by calling `player.loadVideo()` multiple times with several IDs without waiting for one video to be loaded before loading another one.

In at least some occasions, however, I observed this happening when loading multiple videos when I DID wait for each one to be succesfully loaded before loading another one.

Either if this only happened when loading a new video without waiting for the current one to be finished loading, this would still be a bug. Either you forbid calling loadVideo() while one is still loading, and throw an exception when I do so (one that traces back to the place in MY code where I call loadVideo() and with an understandable error message clearly saying that the issue is attempting to load a video while one was pending loading), or you do your job and cancel any pending loading operation and properly destroy your objects and listeners and stuffwhen loadVideo() is called.

**Comment by luwes** [comment]
@teo1978 thanks for the feedback, we will look into this! I have run into this error myself before.

**Comment by vurhd** [comment]
Was there an update to this error? I'm having the same issue when calling player.loadVideo() with different ID's.

**Comment by VasanthCDA** [comment]
I'm also facing this issue. Would be great to get an update on this.
