### ISSUE TITLE
Error with Vimeo Reference randomly

### ISSUE THREAD

**Issue by locvthanh** [vimeo/player.js#936]
### Expected Behavior
Vimeo player is being loaded properly for all user who used our web application

### Actual Behavior
Vimeo player cannot be loaded for some users on both mobile and desktop. The error happened quite random.

### How we integrated with Vimeo
We attach the script from your server using the following html code. This code is in the <head> section of the page

`<script src="https://player.vimeo.com/api/player.js" onerror="alert('Videos may not be available in your country or network. Please check with admin.')"></script>`

Code used to load the library

`try {
  Sentry.addBreadcrumb({
          category: "player",
          message: "loadVimeoPlayer",
          data: options,
          level: "info",
        });

        var player = new Vimeo.Player('vimeo', options);

        var _this = this;
        player.on('ended', (data) => {
          console.log('vimeo ended');
          Sentry.addBreadcrumb({
            category: "player",
            message: "player ended",
            level: "info",
          });
         
          _this.handleOnVideoEnded();
        });

   // do something else here
} catch(e) {
        // console.log('loadVimeoPlayer::error ', e);
        Sentry.addBreadcrumb({
            category: "player",
            message: "loadVimeoPlayer::error when loading vimeo",
            data: e,
            level: "error",
          });
}
`

Error encountered

`{
message: Vimeo is not defined,
name: ReferenceError,
stack:
ReferenceError: Vimeo is not defined
    at a.loadVimeoPlayer (https://stepup.video/app/static/js/app.485939e05f6f492832e6.js:1:86796)
    at a.<anonymous> (https://stepup.video/app/static/js/app.485939e05f6f492832e6.js:1:88445)
    at w (https://stepup.video/app/static/js/vendor.4b47a90e8224094ccaa3.js:24:4778)
    at Generator._invoke (https://stepup.video/app/static/js/vendor.4b47a90e8224094ccaa3.js:24:4566)
    at t.<computed> [as next] (https://stepup.video/app/static/js/vendor.4b47a90e8224094ccaa3.js:24:4957)
    at r (https://stepup.video/app/static/js/vendor.4b47a90e8224094ccaa3.js:29:22440)
    at https://stepup.video/app/static/js/vendor.4b47a90e8224094ccaa3.js:29:22536
}
`

**Comment by rkrishnan8594** [comment]
This error indicates that the player.js script either did not load at all or did not load prior to your code that instantiates the player object (`var player = new Vimeo.Player('vimeo', options);`). In order to confirm the root cause, though, we'll need some way to reproduce the issue.

**Comment by bdougherty** [comment]
My recommendation here would be to bundle the library as part of your build process, or host it yourself. Those users might have some blocking going on that is interfering with the loading of that file.
